Finaliglesia/Models/Ceremonia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Finaliglesia.Models
{
    public class Ceremonia
    {
        public int  CeremoniaID { get; set; }
        public DateTime Fecha { get; set; }
        public string Hora { get; set; }
        [Display(Name ="Sacramento")]
        public int SacramentosId { get; set; }
        public ICollection<Sacramento> Sacramentos { get; set; }
        [Display(Name = "Tipo de Ceremonia")]
        public int TipoCeremoniasId { get; set; }
        public ICollection<Tipoceremonia> TipoCeremonias { get; set; }
        [Display(Name = "Sacerdote")]
        public int SacerdotesId { get; set; }
        public ICollection<Sacerdote> Sacerdotes { get; set; }
        [Display(Name = "Iglesia")]
        public int iglesiaid { get; set; }
        public ICollection<Iglesia> iglesias { get; set; }
    }
}

Finaliglesia/Controllers/CeremoniasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Finaliglesia.Models;

namespace Finaliglesia.Controllers
{
    public class CeremoniasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Ceremonias
        public ActionResult Index()
        {

            return View(db.Ceremonias.ToList());
        }
        public ActionResult ListaCeremonias()
        {
            CeremoniasVistaModelo lista = new CeremoniasVistaModelo();
            return PartialView("_ListaCeremonias", lista.Ceremonias().ToList());
        }
        public JsonResult SacertodesDisponibles(DateTime fecha, string hora) //, string hora
        {

            var SacerdotesId = from Sacerdotes in db.Sacerdotes
                               where
                                     (from Ceremonias in db.Ceremonias
                                      where
                                             Sacerdotes.SacerdoteID == Ceremonias.SacerdotesId &&
                                             Ceremonias.Fecha == fecha &&
                                             Ceremonias.Hora == hora
                                      select new
                                      {
                                          Column1 = 1
                                      }).FirstOrDefault() == null
                               select new
                               {
                                   SacerdoteID = Sacerdotes.SacerdoteID,
                                   Nombre = Sacerdotes.NombreSacerdote+" "+ Sacerdotes.ApellidoSacerdote
                               };
            return Json(new SelectList(SacerdotesId, "SacerdoteID", "Nombre"), JsonRequestBehavior.AllowGet);
        }
        // GET: Ceremonias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ceremonia ceremonia = db.Ceremonias.Find(id);
            if (ceremonia == null)
            {
                return HttpNotFound();
            }
            return View(ceremonia);
        }

        // GET: Ceremonias/Create
        public ActionResult Create()
        {
            
            var tipoceremonia = new SelectList(db.TipoCeremonias.ToList(), "TipoceremoniaID", "Detalle");
            var horas = new SelectList(new[] 
            {
                new { ID="06:00", Name="06:00"},
                new { ID="07:00", Name="07:00"},
                new { ID="08:00", Name="08:00"},
                new { ID="09:00", Name="09:00"},
                new { ID="10:00", Name="10:00"},
                new { ID="11:00", Name="11:00"}
            }, "ID", "Name");
            ViewData["Horas"] = horas;

            var iglesia = new SelectList(db.Iglesias.ToList(), "IglesiaID", "Nombre");
            var sacra = new SelectList(from s in db.Sacramentos select s, "SacramentoID", "DetalleSacramento");
            var sacer = new SelectList(from s in db.Sacerdotes select new { SacerdoteID = s.SacerdoteID, Nombre = s.NombreSacerdote + " " + s.ApellidoSacerdote }, "SacerdoteID", "Nombre");
            ViewData["sacer"] = sacer;
            ViewData["Sacra"] = sacra;
            ViewData["iglesiass"] = iglesia;
            ViewData["tceremons"] = tipoceremonia;
            return View();
        }

        // POST: Ceremonias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CeremoniaID,Fecha,Hora,SacramentosId,TipoCeremoniasId,SacerdotesId,iglesiaid")] Ceremonia ceremonia)
        {
            if (ModelState.IsValid)
            {
                db.Ceremonias.Add(ceremonia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var tipoceremonia = new SelectList(db.TipoCeremonias.ToList(), "TipoceremoniaID", "Detalle");
            var horas = new SelectList(new[]
            {
                new { ID="06:00", Name="06:00"},
                new { ID="07:00", Name="07:00"},
                new { ID="08:00", Name="08:00"},
                new { ID="09:00", Name="09:00"},
                new { ID="10:00", Name="10:00"},
                new { ID="11:00", Name="11:00"}
            }, "ID", "Name");
            ViewData["Horas"] = horas;

            var iglesia = new SelectList(db.Iglesias.ToList(), "IglesiaID", "Nombre");
            var sacra = new SelectList(from s in db.Sacramentos select s, "SacramentoID", "DetalleSacramento");
            var sacer = new SelectList(from s in db.Sacerdotes select new { SacerdoteID = s.SacerdoteID, Nombre = s.NombreSacerdote + " " + s.ApellidoSacerdote }, "SacerdoteID", "Nombre");
            ViewData["sacer"] = sacer;
            ViewData["Sacra"] = sacra;
            ViewData["iglesiass"] = iglesia;
            ViewData["tceremons"] = tipoceremonia;
            return View(ceremonia);
        }

        // GET: Ceremonias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ceremonia ceremonia = db.Ceremonias.Find(id);
            if (ceremonia == null)
            {
                return HttpNotFound();
            }
            return View(ceremonia);
        }

        // POST: Ceremonias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CeremoniaID,Fecha,Hora,SacramentosId,TipoCeremoniasId,SacerdotesId,iglesiaid")] Ceremonia ceremonia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ceremonia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ceremonia);
        }

        // GET: Ceremonias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ceremonia ceremonia = db.Ceremonias.Find(id);
            if (ceremonia == null)
            {
                return HttpNotFound();
            }
            return View(ceremonia);
        }

        // POST: Ceremonias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ceremonia ceremonia = db.Ceremonias.Find(id);
            db.Ceremonias.Remove(ceremonia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Finaliglesia/Views/Ceremonias/Create.cshtml
@model Finaliglesia.Models.Ceremonia

@{
    ViewBag.Title = "Crear";
}

<h2> Crear Creremonia</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      @*  <h4>Ceremonia</h4>*@
        <div>
            @Html.ActionLink("Ceremonias Existentes", "Index", "Ceremonias", null, new { @class = "btn btn-primary" })
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Hora, ViewData["Horas"] as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Hora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SacramentosId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SacramentosId, ViewData["Sacra"] as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SacramentosId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoCeremoniasId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoCeremoniasId, ViewData["tceremons"] as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoCeremoniasId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SacerdotesId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SacerdotesId, ViewData["sacer"] as SelectList, new { @class = "form-control" })
                
                @Html.ValidationMessageFor(model => model.SacerdotesId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iglesiaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.iglesiaid, ViewData["iglesiass"] as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iglesiaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-primary form-control" />
            </div>
        </div>
    </div>
} 

<div>
    @Html.ActionLink("Regresar", "Index","MiembroCeremonias", new { @class = "btn btn-primary" })
</div>
@section Scripts{
    @Scripts.Render("/bundles/jqueryval")
    <script>
    $(".datepicker").datepicker({
        format: 'yyyy-mm-dd',
        autoclose: true,
        lannguaje:'es'
    });
    </script>
    @*<script src="../../Scripts/jquery-1.7.1.js" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>*@
<script type="text/javascript">

    $(document).ready(function () {
       
        //Dropdownlist Selectedchange event
        $("#Hora").change(function () {
            $("#SacerdotesId").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("SacertodesDisponibles")', // we are calling json method
                dataType: 'json',
                data: { fecha: $("#Fecha").val(), hora: $("#Hora").val()}, //, fecha: $("#Hora").val(),
               // here we are get value of selected country and passing same value
                success: function (states) {
                    $.each(states, function (i, state) {
                        $("#SacerdotesId").append('<option value="' + state.Value + '">' + state.Text + '</option>');
                    // here we are adding option for States
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex.error);
                }
            });
            return false;
        })
    });
</script>  
}

Finaliglesia/Views/Ceremonias/Delete.cshtml
@model Finaliglesia.Models.Ceremonia

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar Ceremonia</h2>

@*<h3>Are you sure you want to delete this?</h3>*@
<div>
    @*<h4>Ceremonia</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hora)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hora)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SacramentosId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SacramentosId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCeremoniasId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCeremoniasId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SacerdotesId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SacerdotesId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.iglesiaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.iglesiaid)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-primary form-control" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

Finaliglesia/Views/Ceremonias/Details.cshtml
@model Finaliglesia.Models.CeremoniasModeloVista

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Ceremonia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hora)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hora)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SacramentosId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCeremoniasId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCeremoniasId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SacerdotesId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SacerdotesId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.iglesiaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.iglesiaid)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.CeremoniaID }) |
    @Html.ActionLink("Regresar", "Index")
</p>

Finaliglesia/Views/Ceremonias/Edit.cshtml
@model Finaliglesia.Models.Ceremonia

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Ceremonia</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      @*  <h4>Ceremonia</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CeremoniaID)

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SacramentosId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SacramentosId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SacramentosId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoCeremoniasId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoCeremoniasId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoCeremoniasId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SacerdotesId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SacerdotesId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SacerdotesId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iglesiaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.iglesiaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.iglesiaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-primary form-control" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Finaliglesia/Views/Ceremonias/Index.cshtml
@model IEnumerable<Finaliglesia.Models.Ceremonia>

@{
    ViewBag.Title = "Ceremonias";
}

<h2>Lista de Cereminias</h2>

<div>
    @Html.ActionLink("Regresar", "Index", "MiembroCeremonias",null, new { @class = "btn btn-primary" })
</div>
<br />
<div id="ceremonias2"></div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
    $(document).ready(
        $("#ceremonias2").load('/Ceremonias/ListaCeremonias')
        );

    </script>
}